### ISSUE TITLE
Does Version 6.2 Solve the Issue Where Some PDFs Won't Print?

### ISSUE THREAD

**Issue by RedSoxFan04** [pdewacht/brlaser#152]

**Comment by DrewBrunning** [comment]
This is duplicative of #52 
I had this issue even building from source until manually applying the fix. I don't believe it's addressed in the latest version based on my testing.

**Comment by RedSoxFan04** [comment]
> This is duplicative of #52 I had this issue even building from source until manually applying the fix. I don't believe it's addressed in the latest version based on my testing.

Oh, okay. After I read your message late last night, I set about manually applying the fix with great determination. And I succeeded! It's so great to finally be able to print anything after all this time! And it wasn't as hard as I thought!

**Comment by sjuk** [comment]
The issue is still there on Ubuntu 20.04 witch package printer-driver-brlaser 6-1build1 installed.
If understanding correctly the latest release brlaser v6 in this git repository does not contain the fix from #52 yet.
How probable is it to see the fix from #52 in the next brlaser release?
